import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist_Mono } from "next/font/google";
import { inisialisasiZodBahasaIndonesia } from "@/utils/zod-indonesia";
import "./globals.css";

inisialisasiZodBahasaIndonesia();

// 🚀 LANGKAH 2: Konfigurasi Plus Jakarta Sans Secara Lokal
const plusJakartaSans = Plus_Jakarta_Sans({
    variable: "--font-plus-jakarta-sans", // 🌟 Nama variabel disesuaikan dengan isi globals.css Anda
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800"], // Memuat ketebalan font lengkap
    display: "swap",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${plusJakartaSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
